# --- Jekyll Config --- 
name: Starbound Server
url: "https://starbound.debears.org"
remote_theme: pmarsceill/just-the-docs
color_scheme: "dark"
search_enabled: false
logo: "protectorate.png"
heading_anchors: false
aux_links:
  "⬇️Download Modpack (Primary Link)":
    - "//drive.google.com/u/0/uc?export=download&confirm=HjCC&id=139nlH235YnqkVfewnJnNqymN_GNvIZCa"
aux_links_new_tab: false

# --- Misc ---

# Output options (more information on Jekyll's site)
timezone: "America/Toronto"
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM

# Exclude these files from production site
exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/

# --- Plugins ---

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-paginate
#  - jekyll-sitemap
