# --- Jekyll Config --- 

# Name of website
name: Starbound Server
url: "https://ebears.github.io/starbound.web/"
remote_theme: pmarsceill/just-the-docs

color_scheme: dark
logo: "https://i.ibb.co/0Md6WK5/hd-starbound-protectorate-logo-by-zeminio-dc8p07x-fullview.png"

# Enable or disable the site search
# Supports true (default) or false
search_enabled: true

search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 2
  # Maximum amount of previews per search result
  # Default: 3
  previews: 3
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 5
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 10
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: false

# Aux links for the upper right navigation
aux_links:
  "⬇️ Download Modpack":
    - "//files.debears.org/filebrowser/share/fbc8mCMv"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

heading_anchors: true
footer_content:
last_edit_timestamp: false
gh_edit_link: false

# --- Misc ---

collections:
  modpack:
    permalink: "https://starbound.debears.org/#-server-modpack-required"
    output: true
  info:
    permalink: "https://starbound.debears.org/#-info-about-the-server"
    output: true

just_the_docs:
  collections:
    modpack:
      name: Modpack
    info:
      name: Tutorials

# Output options (more information on Jekyll's site)
timezone: "America/Toronto"
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM

# Exclude these files from production site
exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/

# --- Plugins ---

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
#  - jekyll-paginate
#  - jekyll-sitemap
