# --- Jekyll Config --- 
name: The Island | Starbound Server
url: "https://starbound.debears.org"
remote_theme: pmarsceill/just-the-docs
color_scheme: "light"
search_enabled: true
logo: "media/protectorate.png"
heading_anchors: false
aux_links:
  "⬇️Modpack Version 1.1.0 Download":
    - "//drive.google.com/file/d/1V3eHzatV5z124mU9rfEVlAAMAKgrQKMb/view?usp=sharing"
aux_links_new_tab: true

# --- Misc ---

# Output options (more information on Jekyll's site)
timezone: "America/Toronto"
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM

# Exclude these files from production site
exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/

# --- Plugins ---

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-paginate
#  - jekyll-sitemap
